server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8087/
          predicates:
            - Path=/employee/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header
        - id: consumerModule
          uri: http://localhost:8088/
          predicates:
            - Path=/consumer/**
          filters:
            - AddRequestHeader=second-request, second-request-header
            - AddResponseHeader=second-response, second-response-header